name: Builds
on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    name: Building distribution
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: '3.8'
            numpy: '1.16'
            source: false
          - os: ubuntu-latest
            python: '3.9'
            numpy: '1.19'
            source: false
          - os: ubuntu-latest
            python: '3.10'
            numpy: '1.21'
            source: true
          - os: macos-latest
            python: '3.8'
            numpy: '1.16'
            source: false
          - os: macos-latest
            python: '3.9'
            numpy: '1.19'
            source: false
          - os: macos-latest
            python: '3.10'
            numpy: '1.21'
            source: false
          - os: windows-latest
            python: '3.8'
            numpy: '1.16'
            source: false
          - os: windows-latest
            python: '3.9'
            numpy: '1.19'
            source: false
          - os: windows-latest
            python: '3.10'
            numpy: '1.21'
            source: false

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: hydride
          auto-update-conda: true
          python-version: ${{ matrix.python }}
      - name: Installing dependencies
        run: conda install -c conda-forge numpy=$NUMPY_VERSION "cython>=0.29" "biotite=0.28" "msgpack-python>=1.0"
        env:
          NUMPY_VERSION: ${{ matrix.numpy }}
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Installing 'rename'
        run: sudo apt install rename
      - name: Building wheel distribution
        run: python setup.py bdist_wheel
      - if: ${{ matrix.source }}
        name: Building source distribution
        run: python setup.py sdist
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Correct distribution file name
        run: rename 's/linux/manylinux1/g' dist/*.whl
      - uses: actions/upload-artifact@v2
        with:
          name: Hydride distribution
          path: dist//*
          if-no-files-found: error


  doc:
    name: Building documentation

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: hydride
          auto-update-conda: true
          python-version: '3.9'
      - name: Installing dependencies
        run: conda install -c conda-forge sphinx cython numpy numpydoc biotite
      - name: Building documentation
        run: sphinx-build ./doc ./build/doc
      - name: Zipping documentation
        run: cd .//build; zip -r doc.zip doc; cd ..
      - uses: actions/upload-artifact@v2
        with:
          name: Hydride documentation
          path: build//doc.zip
          if-no-files-found: error